version: 2

updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    open-pull-requests-limit: 10

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    groups:
      eslint-related:
        dependency-type: development
        patterns:
          - eslint
          - eslint-*
          - "@*/eslint-plugin"
          - typescript-eslint
          - globals
      babel-related:
        dependency-type: development
        patterns:
          - "@babel/*"
          - core-js
      jest-related:
        dependency-type: development
        patterns:
          - jest
          - ts-jest

    assignees:
      - manferlo81
