version: 2

updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    open-pull-requests-limit: 10

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    groups:
      eslint-related:
        dependency-type: development
        patterns:
          - eslint
          - eslint-plugin
          - globals

    assignees:
      - manferlo81
