name: CI
run-name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  job_lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Lint
        run: npm run lint

  job_test_and_build:
    strategy:
      matrix:
        os:
          - name: Ubuntu
            machine: ubuntu-latest
          - name: Windows
            machine: windows-latest
          - name: macOS
            machine: macos-latest
        node-version:
          - 18.x
          - 20.x
          - 21.x
          - 22.x

    name: Test and Build ( ${{ matrix.os.name }}, Node.js v${{ matrix.node-version }} )

    needs: job_lint
    runs-on: ${{ matrix.os.machine }}

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: npm test
        env:
          NO_COVERAGE: true

      - name: Build
        run: npm run build

  job_upload_coverage:
    name: Upload coverage to Codecov

    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}
    needs: job_test_and_build
    runs-on: ubuntu-latest

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Run Tests
        run: npm test
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json

  job_create_release:
    name: Create GitHub Release

    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    needs: job_test_and_build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Build
        run: npm run build

      - name: Create Tarball
        run: npm pack

      - name:
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: romanint-*.tgz

  job_publish_to_npm:
    name: Publish package to npm

    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    needs: job_test_and_build
    runs-on: ubuntu-latest

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  job_publish_to_gpr:
    name: Publish package to GitHub Packages

    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    needs: job_test_and_build
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
