name: Lint, Test and Build

on:
  workflow_call:
  workflow_dispatch:

env:
  DEFAULT_NODE_VERSION: 20.x

jobs:
  job_lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout, Setup Node.js v${{ env.DEFAULT_NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Lint
        run: npm run lint

  job_test_and_build:
    strategy:
      matrix:
        os:
          - name: Windows
            machine: windows-latest
          - name: Ubuntu
            machine: ubuntu-latest
          - name: macOS
            machine: macos-latest

        node-version:
          - 18.x
          - 20.x
          - 21.x
          - 22.x

    name: Test and Build ( ${{ matrix.os.name }}, Node.js v${{ matrix.node-version }} )

    runs-on: ${{ matrix.os.machine }}
    needs: job_lint

    steps:
      - name: Checkout, Setup Node.js v${{ matrix.node-version }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: npm test
        env:
          SKIP_COVERAGE: true

      - name: Build
        run: npm run build
